# Project Name
TARGET = FROG

#

# Sources
CPP_SOURCES = FROG.cpp
CPP_SOURCES += eeprom.cpp
CPP_SOURCES += rgbLeds.cpp
CPP_SOURCES += RMSMeter.cpp

INC_DIR = ../
# Library Locations
LIBDAISY_DIR = ../../libDaisy/
DAISYSP_DIR = ../../DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

